/*
 * C ABI around the Lean engine. This is the *only* C in the project.
 *
 *   mathengine_init()              -- initialize the Lean runtime + module (call once)
 *   mathengine_call(const char*)   -- JSON-RPC request in, JSON-RPC response out (caller frees)
 *
 * Emscripten exports these to JS (see scripts/build-wasm.sh); the native test (c/test.c)
 * exercises the identical call path, so the wasm build only adds the toolchain, not new code.
 */
#include <lean/lean.h>
#include <stdlib.h>
#include <string.h>
#ifdef __EMSCRIPTEN__
#include <emscripten.h>
#define KEEP EMSCRIPTEN_KEEPALIVE
#else
#define KEEP
#endif

/* Generated by `lake build` from MathEngine.lean / @[export mathengine_handle] */
extern void lean_initialize_runtime_module(void);
extern lean_object* initialize_MathEngine(uint8_t builtin, lean_object* w);
extern lean_object* mathengine_handle(lean_object* request);

KEEP int mathengine_init(void) {
  lean_initialize_runtime_module();
  lean_object* res = initialize_MathEngine(1 /* builtin */, lean_io_mk_world());
  if (lean_io_result_is_error(res)) { lean_io_result_show_error(res); lean_dec(res); return 1; }
  lean_dec_ref(res);
  lean_io_mark_end_initialization();
  return 0;
}

KEEP char* mathengine_call(const char* request) {
  lean_object* req = lean_mk_string(request);          /* owned */
  lean_object* res = mathengine_handle(req);            /* consumes req, returns owned string */
  char* out = strdup(lean_string_cstr(res));
  lean_dec(res);
  return out;
}

KEEP void mathengine_free(char* s) { free(s); }
